# Generated by Django 3.2 on 2022-09-21 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiel',
            new_name='Profile',
        ),
        migrations.AlterField(
            model_name='useradress',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Other', 'Other'), ('Academy', 'Academy'), ('Office', 'Office')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userphonenumper',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Other', 'Other'), ('Academy', 'Academy'), ('Office', 'Office')], max_length=10),
        ),
    ]
