# Generated by Django 3.2 on 2022-11-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220928_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradress',
            name='type',
            field=models.CharField(choices=[('Other', 'Other'), ('Home', 'Home'), ('Academy', 'Academy'), ('Office', 'Office')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userphonenumper',
            name='type',
            field=models.CharField(choices=[('Other', 'Other'), ('Home', 'Home'), ('Academy', 'Academy'), ('Office', 'Office')], max_length=10),
        ),
    ]
