# Generated by Django 3.2 on 2022-09-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('sale', 'sale'), ('feature', 'feature'), ('new', 'new'), ('old', 'old')], max_length=10, verbose_name='Flag'),
        ),
    ]
