# Generated by Django 3.2 on 2022-11-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('new', 'new'), ('old', 'old'), ('feature', 'feature'), ('sale', 'sale')], max_length=10, verbose_name='Flag'),
        ),
    ]
